version: "3"
services:
  news:
    build:
      context: .
    container_name: news
    command: sh -c "python manage.py runserver  0.0.0.0:8000"
    ports:
      - "8003:8000"

  postgresdb:
    image: 'postgres:16'
    hostname: 'distributor'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '5434:5432'
    volumes:
      - 'distributor-postgres-data:/var/lib/postgresql/data'
volumes:
  distributor-postgres-data: